version: '3.8'

services:
  client:
    build:
      context: ./client
    container_name: next-client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - server
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  server:
    build:
      context: ./server
    container_name: next-node-server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: next-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql-next
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
