// src/errors/errorCodes.js
export const ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_BLOCKED: 'USER_BLOCKED',
  ACCOUNT_NOT_ACTIVE: 'ACCOUNT_NOT_ACTIVE',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  SERVER_ERROR: 'SERVER_ERROR', // Przykładowy dodatkowy kod
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  CSRF_TOKEN_INVALID: 'CSRF_TOKEN_INVALID',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  INVALID_REQUEST: 'INVALID_REQUEST'
} as const; // 'as const' zapewnia, że wartości są traktowane jako literały