name: CI - Next.js Build and Test

# Uruchomienie akcji przy każdym pushu lub pull request
on:
  push:
    branches:
      - main  # Uruchomienie na push do gałęzi 'main'
  pull_request:
    branches:
      - main  # Uruchomienie na pull request do gałęzi 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Wybór systemu operacyjnego do uruchomienia akcji

    steps:
      # Krok 1: Sprawdzenie kodu źródłowego
      - name: Checkout repository
        uses: actions/checkout@v2

      # Krok 2: Zainstalowanie Node.js (wersja 16)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Wybierz wersję Node.js

      # Krok 3: Instalacja zależności
      - name: Install dependencies
        run: npm install

      # Krok 4: Uruchomienie testów (przykład z użyciem Jest)
      - name: Run tests
        run: npm run test

      # Krok 5: Budowanie aplikacji (np. produkcyjna wersja)
      - name: Build application
        run: npm run build

      # Krok 6: Uruchomienie aplikacji (opcjonalnie, np. do testów)
      - name: Start application
        run: npm start &
