name: Build and Deploy Next.js Client

on:
  workflow_dispatch:  # ręczne uruchomienie z Run workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies (client folder)
        run: |
          cd client
          npm install

      - name: Build and export Next.js
        run: |
          cd client
          npm run build
          npm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/out
